// src/components/Screen.tsx
'use client'

import { useState } from 'react'
import Library from './Library'
import TracksPlayer from './TracksPlayer'
// Barre latérale rétractable pour le lecteur
import CollapsibleSidebar from './CollapsibleSidebar'
// Modale d'import/export
import SettingsModal from './SettingsModal'
import { useCookieState } from '@/hooks/useCookieState'
import { usePlayerQueue } from '@/hooks/usePlayerQueue'
import { usePresentationWindow } from '@/hooks/usePresentationWindow'
import { useTrackLink } from '@/hooks/useTrackLink'

export default function Screen() {
  const { tracks, addTrack, updateTrack, removeTrack, removeAllTracks } = usePlayerQueue()
  const { present, openViewer } = usePresentationWindow()

  const [showSettings, setShowSettings] = useState(false)
  const [isPlayerCollapsed, setIsPlayerCollapsed] = useCookieState('playerCollapsed', false, {
    trueValue: 'true',
    falseValue: 'false',
  })

  // Register logic that handles ?trackId= links and inter-tab communication
  const { toastMessage, externalMessage } = useTrackLink(addTrack)

  return (
    <div
      className={`min-h-screen bg-gray-900 grid ${
        isPlayerCollapsed ? 'grid-cols-[1fr_1.5rem]' : 'grid-cols-[1fr_24rem]'
      }`}
    >
      {/* Error notification for invalid track links */}
      {toastMessage && (
        <div className="fixed top-2 left-1/2 -translate-x-1/2 bg-red-600 text-white px-3 py-2 rounded z-50">
          {toastMessage}
        </div>
      )}

      {/* Inform the user that another tab already runs the application */}
      {externalMessage && (
        <div
          className="fixed inset-0 bg-black/70 flex items-center justify-center z-50"
          tabIndex={0}
        >
          <div className="bg-gray-800 p-6 rounded flex flex-col items-center gap-4">
            {/* Message interne à l'application, il contient une balise <br>. */}
            <p
              className="text-white text-center"
              dangerouslySetInnerHTML={{ __html: externalMessage }}
            />
          </div>
        </div>
      )}

      <div className="p-8 overflow-auto min-w-[522px]">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold text-purple-400 mb-8">MJ Screen Jukebox</h1>
        </div>

        <div className="space-y-6">
          <Library onPlayAudio={addTrack} onOpenImage={present} />
        </div>
      </div>

      <CollapsibleSidebar
        collapsed={isPlayerCollapsed}
        onCollapsedChange={setIsPlayerCollapsed}
        onOpenSettings={() => setShowSettings(true)}
      >
        <TracksPlayer
          tracks={tracks}
          onUpdateTrack={updateTrack}
          onRemoveTrack={removeTrack}
          onRemoveAllTracks={removeAllTracks}
          onOpenViewer={openViewer}
        />
      </CollapsibleSidebar>

      <SettingsModal isOpen={showSettings} onClose={() => setShowSettings(false)} />
    </div>
  )
}

// src/components/Screen.vue
<template>
  <div class="min-h-screen bg-gray-900 grid" :class="isPlayerCollapsed ? 'grid-cols-[1fr_1.5rem]' : 'grid-cols-[1fr_24rem]'">
    <!-- Error notification for invalid track links -->
    <div v-if="toastMessage" class="fixed top-2 left-1/2 -translate-x-1/2 bg-red-600 text-white px-3 py-2 rounded z-50">
      {{ toastMessage }}
    </div>

    <!-- Inform the user that another tab already runs the application -->
    <div v-if="externalMessage" class="fixed inset-0 bg-black/70 flex items-center justify-center z-50" tabindex="0">
      <div class="bg-gray-800 p-6 rounded flex flex-col items-center gap-4">
        <p class="text-white text-center" v-html="externalMessage"/>
      </div>
    </div>
    <div class="p-8 overflow-auto min-w-[522px]">
      <div class="flex items-center justify-between">
        <h1 class="text-3xl font-bold text-purple-400 mb-8">MJ Screen Jukebox</h1>
      </div>

      <div class="space-y-6">
        <Library ref="library" @play-audio="handlePlayAudio" @open-image="handleOpenImage" />
      </div>
    </div>

    <CollapsibleSidebar v-model:collapsed="isPlayerCollapsed" @open-settings="handleOpenSettings">
      <TracksPlayer ref="tracksPlayer" @open-viewer="handleOpenViewer" />
    </CollapsibleSidebar>

    <SettingsModal
      :isOpen="showSettings"
      @close="showSettings = false" />

  </div>
</template>

<script lang="ts">
  import { defineComponent, ref, watch } from 'vue';
  import Library from './Library.vue';
  import TracksPlayer from './TracksPlayer.vue';
  // Bouton ouvrant la modale d'import/export
  import SettingsModal from './SettingsModal.vue';
  // Barre latérale rétractable pour le lecteur
  import CollapsibleSidebar from './CollapsibleSidebar.vue';
  import FileTrack from '../models/FileTrack'
  import GalleryImage from '@/models/GalleryImage'
  import { Cookies } from '../models/Cookies';
  import { useTrackLink } from '@/composables/useTrackLink';

  export default defineComponent({
    name: 'Screen',
    components: {
      Library,
      TracksPlayer,
      SettingsModal,
      CollapsibleSidebar,
    },
    setup() {
      type LibraryInstance = InstanceType<typeof Library> & { openImageViewer: () => void };

      const library = ref<LibraryInstance | null>(null);
      const tracksPlayer = ref<InstanceType<typeof TracksPlayer> | null>(null);
      const showSettings = ref(false)

      // Add the selected track to the player queue
      const handlePlayAudio = (track: FileTrack) => {
        if (tracksPlayer.value) {
          tracksPlayer.value.addTrack(track)
        }
      }

      const handleOpenImage = (_image: GalleryImage) => {
        // the library component manages the modal presentation; hook provided for extensibility
      }

      const handleOpenViewer = () => {
        library.value?.openImageViewer()
      }

      // Register logic that handles ?trackId= links and inter-tab communication
      const { toastMessage, externalMessage } = useTrackLink(handlePlayAudio)

      const isPlayerCollapsed = ref(Cookies.get('playerCollapsed') === 'true');
      watch(isPlayerCollapsed, val => {
        Cookies.set('playerCollapsed', val ? 'true' : 'false');
      });

      const handleOpenSettings = () => {
        showSettings.value = true
      }

      return {
        library,
        tracksPlayer,
        handlePlayAudio,
        handleOpenImage,
        handleOpenViewer,
        isPlayerCollapsed,
        handleOpenSettings,
        showSettings,
        toastMessage,
        externalMessage,
      };
    },
  });
</script>
