// src/components/Uploader.vue
<template>
    <label class="w-8 cursor-pointer bg-purple-600 hover:bg-purple-500 px-2 py-1
            rounded-lg flex items-center gap-2 transition-colors justify-center">

      <Plus/>
      <input type="file"
              accept="audio/*,image/*"
              @change="handleFileChange"
              class="hidden" />
    </label>
</template>

<script lang="ts">
  import { defineComponent } from 'vue';

  export default defineComponent({
    name: 'Uploader',
    // On remplace `methods` par une fonction `setup()`
    setup(_, { emit }) {
      const handleFileChange = (event: Event) => {
        const file = (event.target as HTMLInputElement).files?.[0];
        if (file) {
          emit('file-selected', file);
        }
      };

      // On retourne ce qu'on veut exposer au template
      return {
        handleFileChange
      };
    }
  });
</script>

// src/components/Uploader.tsx
'use client'

import { Plus } from 'lucide-react'
import type { ChangeEvent } from 'react'

interface UploaderProps {
  onFileSelected: (file: File) => void
}

export default function Uploader({ onFileSelected }: UploaderProps) {
  function handleFileChange(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]
    if (file) {
      onFileSelected(file)
    }
  }

  return (
    <label
      className="w-8 cursor-pointer bg-purple-600 hover:bg-purple-500 px-2 py-1
            rounded-lg flex items-center gap-2 transition-colors justify-center"
    >
      <Plus />
      <input type="file" accept="audio/*,image/*" onChange={handleFileChange} className="hidden" />
    </label>
  )
}
